// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swznjgwpwxivomntftwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3em5qZ3dwd3hpdm9tbnRmdHd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MjMxOTIsImV4cCI6MjA3NDI5OTE5Mn0.cVSee1KZOqdDhsPq4xu9gCj6dFUy9CpSgy0ZFRJmJDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});