// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htywmazgmcqwwwjvcigw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0eXdtYXpnbWNxd3d3anZjaWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MTMwOTYsImV4cCI6MjA3ODE4OTA5Nn0.V-UlTDSaTPDzcnKEIIQ2Jho9Y11CH6ffVGj5t9kugVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});